---
title: "Day 2"
output: html_notebook
---

```{r setup, echo = FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(dplyr)
library(tidyr)
library(purrr)

```

# Part One

Load:

```{r}
day2 <- read.table(file = paste0(getwd(), "/data/day2.txt")
                   , header = FALSE
                   , fill = TRUE)
day2.ex <- read.table(file = paste0(getwd(), "/data/day2_part1_sample.txt")
                      , header = FALSE
                      , fill = TRUE)
```

## Exploration

```{r}
#i want the following structure:
#game # (top level)
## draw attempt # (2nd level)
### draw attempt color (3rd level)
### draw attempt value (3rd level)

#so that ultimately we can recollect into long format and do whatever analysis we want.

try1 <- read.table(file = paste0(getwd(), "/data/day2_part1_sample.txt")
           , header = FALSE
           , fill = TRUE
           , sep = "\n"
           , row.names = NULL)

#row num corresponds to each game, so remove all text before each colon
try1 <- try1 %>% 
  dplyr::mutate(V1 = gsub(".*: ", "", V1)
                , game = row_number()) %>% #add back in row num in 'game' col
  dplyr::select(game, V1)

#extract strings in nested list structure: first extract based on ';'
#second extract based on ','
try1 %>%
  tidyr::unnest_wider(
    sapply(try1$V1, FUN = function(x){
    str_split_1(x, "; ")
}, simplify = TRUE, USE.NAMES = FALSE) %>%
  sapply(., FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
)

first.splitting <- sapply(try1$V1, FUN = function(x){
    str_split_1(x, "; ")
}, simplify = TRUE, USE.NAMES = FALSE)

nested1 <- try1 %>%
  tibble(.
            , draw = first.splitting
) %>%
  tidyr::unnest_wider(
    draw
, names_sep = "_"
)

# big.split <- sapply(try1$V1, FUN = function(x){
#     str_split_1(x, "; ")
# }, simplify = TRUE, USE.NAMES = FALSE) %>%
#   sapply(., FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)


nested2 <- nested1 %>%
  tibble(.
         , detail_1 = sapply(nested1$draw_1
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
       , detail_2 = sapply(nested1$draw_2
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
       , detail_3 = sapply(nested1$draw_3
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)) %>%
  tidyr::unnest_wider(detail_1, names_sep = "_") %>%
  tidyr::unnest_wider(detail_2, names_sep = "_") %>%
  tidyr::unnest_wider(detail_3, names_sep = "_")

nested2 <- nested2 %>%
  dplyr::select(-V1) %>%
  tidyr::pivot_longer(.
                               , cols = contains("detail")) %>%
  dplyr::mutate(item_num = str_split(name, pattern = ".*_", simplify = TRUE)[,2]
                , draw_num = str_split(name, pattern = "_", simplify = TRUE)[,2]
                , draw_value = str_split(value, pattern = " ", simplify = TRUE)[,1] %>%
                  as.numeric(.)
                , draw_color = str_split(value, " ", simplify = TRUE)[,2]) %>%
  dplyr::select(-draw_1, -draw_2, -draw_3, -name, -value)
```

Analysis:

```{r}
#12 red cubes, 13 green cubes, and 14 blue cubes
nested2 %>%
  dplyr::filter(!is.na(draw_value)) %>%
  dplyr::group_by(game) %>%
  dplyr::filter(!any((draw_color == "red" & draw_value > 12) |
                  (draw_color == "green" & draw_value > 13) |
                  (draw_color == "blue" & draw_value > 14))
  ) %>%
  ungroup() %>%
  distinct(game) %>%
  sum(.)
```

## Proposed Solution, But A Bad One

```{r}
try2 <- read.table(file = paste0(getwd(), "/data/day2.txt")
           , header = FALSE
           , fill = TRUE
           , sep = "\n"
           , row.names = NULL)

#row num corresponds to each game, so remove all text before each colon
try2 <- try2 %>% 
  dplyr::mutate(V1 = gsub(".*: ", "", V1)
                , game = row_number()) %>% #add back in row num in 'game' col
  dplyr::select(game, V1)

#extract strings in nested list structure: first extract based on ';'
#second extract based on ','
# try1 %>%
#   tidyr::unnest_wider(
#     sapply(try1$V1, FUN = function(x){
#     str_split_1(x, "; ")
# }, simplify = TRUE, USE.NAMES = FALSE) %>%
#   sapply(., FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
# )

first.splitting2 <- sapply(try2$V1, FUN = function(x){
    str_split_1(x, "; ")
}, simplify = TRUE, USE.NAMES = FALSE)

nested1.2 <- try2 %>%
  tibble(.
            , draw = first.splitting2
) %>%
  tidyr::unnest_wider(
    draw
, names_sep = "_"
)

# big.split <- sapply(try1$V1, FUN = function(x){
#     str_split_1(x, "; ")
# }, simplify = TRUE, USE.NAMES = FALSE) %>%
#   sapply(., FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)


nested2.2 <- nested1.2 %>%
  tibble(.
         , detail_1 = sapply(nested1.2$draw_1
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
         , detail_2 = sapply(nested1.2$draw_2
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
         , detail_3 = sapply(nested1.2$draw_3
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
                  , detail_4 = sapply(nested1.2$draw_4
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
                  , detail_5 = sapply(nested1.2$draw_5
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
                  , detail_6 = sapply(nested1.2$draw_6
                             , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
  ) %>%
  tidyr::unnest_wider(detail_1, names_sep = "_") %>%
  tidyr::unnest_wider(detail_2, names_sep = "_") %>%
  tidyr::unnest_wider(detail_3, names_sep = "_") %>%
  tidyr::unnest_wider(detail_4, names_sep = "_") %>%
  tidyr::unnest_wider(detail_5, names_sep = "_") %>%
  tidyr::unnest_wider(detail_6, names_sep = "_")

nested2.2 <- nested2.2 %>%
  dplyr::select(-V1) %>%
  tidyr::pivot_longer(.
                               , cols = contains("detail")) %>%
  dplyr::mutate(item_num = str_split(name, pattern = ".*_", simplify = TRUE)[,2]
                , draw_num = str_split(name, pattern = "_", simplify = TRUE)[,2]
                , draw_value = str_split(value, pattern = " ", simplify = TRUE)[,1] %>%
                  as.numeric(.)
                , draw_color = str_split(value, " ", simplify = TRUE)[,2]) %>%
  dplyr::select(-draw_1, -draw_2, -draw_3, -draw_4, -draw_5, -draw_6, -name, -value)
```

```{r}
#12 red cubes, 13 green cubes, and 14 blue cubes
nested2.2 %>%
  dplyr::filter(!is.na(draw_value)) %>%
  dplyr::group_by(game) %>%
  dplyr::filter(!any((grepl("red", draw_color) & draw_value > 12) |
                  (grepl("green", draw_color) & draw_value > 13) |
                  (grepl("blue", draw_color) & draw_value > 14))
  ) %>%
  ungroup() %>%
  distinct(game) %>%
  sum(.)
```

# Part Two

Even though my solution in part one was overkill, the table structure makes part 2 easier.

```{r}
#get min num of draws per game, then get power for each game, then sum
nested2.2 %>%
  dplyr::filter(!is.na(draw_value)) %>%
  dplyr::group_by(game, draw_color) %>%
  dplyr::summarize(min_draw_num = max(draw_value)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(game) %>%
  dplyr::summarize(power = prod(min_draw_num)) %>%
  dplyr::select(power) %>%
  sum(.)
```


```{r}
#TODO: trying to generalize the creation of detail_1, detail_2, ... in part 1
chk <- map_dfc(
  colnames(nested1)[grepl("detail", colnames(nested1))], 
  ~ unnest_wider(sapply(nested1[.x]
                        , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
                 , .x
                 , names_sep = "_")
)

chk2 <- map_dfc(colnames(nested1)[grepl("detail", colnames(nested1))], 
     ~ nested1 %>% 
          select(.x) %>%
         unnest_wider(sapply(.x
                        , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
                      , names_sep = "_"))


chk <- nested1 %>%
  tibble(.
         , detail_1 = sapply(nested1$draw_1
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
       , detail_2 = sapply(nested1$draw_2
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)
       , detail_3 = sapply(nested1$draw_3
       , FUN = function(x) {str_split(x, ", ")}, USE.NAMES = FALSE)) %>%
  tidyr::unnest_wider(detail_1, names_sep = "_") %>%
  tidyr::unnest_wider(detail_2, names_sep = "_") %>%
  tidyr::unnest_wider(detail_3, names_sep = "_")
```

